version: "3"

services:
  mysql-development:
    build:
      context: .
      dockerfile: Dockerfile.db.test
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  nestjs-server:
    depends_on:
      - "mysql-development"
    build: .
    command: yarn workspace @workout-logger/nestjs-server run start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
