version: "3"

services:
  mysql-testing:
    build:
      context: .
      dockerfile: Dockerfile.db.test
    environment:
      MYSQL_ROOT_PASSWORD: password
    security_opt:
      - seccomp:unconfined
  test:
    depends_on:
      - "mysql-testing"
    build: .
    command: npm run test
    volumes:
      - .:/app
  test-watch:
    depends_on:
      - "mysql-testing"
    build: .
    command: npm run test:watch
    volumes:
      - .:/app
  test-coverage:
    depends_on:
      - "mysql-testing"
    build: .
    command: npm run test:coverage
    volumes:
      - .:/app
