version: '3'

services:
  mysql-development:
    build:
      context: .
      dockerfile: Dockerfile.db.test
    environment:
      MYSQL_ROOT_PASSWORD: password
<<<<<<< HEAD
    ports:
      - "3307:3306"
    security_opt:
      - seccomp:unconfined
=======
      MYSQL_DATABASE: workout_logger_db
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
>>>>>>> develop
  wl-node:
    build: .
    command: npm run dev
    ports: 
      - "5000:5000"
    volumes:
      - .:/app
    depends_on: 
      - "mysql-development"