version: '3'

services:
  mysql-development:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: workout_logger_db
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  wl-node:
    build: .
    command: npm run dev
    ports: 
      - "5000:5000"
    volumes:
      - .:/app
    depends_on: 
      - "mysql-development"
volumes:
  my-datavolume: